apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: xview
  labels: 
    app: ui
    part-of: xview
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels: 
      app: ui
  template:
    metadata:
      labels: 
          app: ui
          part-of: xview
    spec:
      serviceAccountName: ui-service-account
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: ui
        image: localhost/ui:cpu
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 8000
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        envFrom:
        - configMapRef: 
            name: app-config
        - secretRef: 
            name: app-secret
        readinessProbe:
          httpGet: 
            path: "/healthz" 
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet: 
            path: "/healthz"
            port: http 
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests: 
            cpu: "100m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: datasets
          mountPath: /data
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: xview
spec:
  selector: 
    app: ui
  ports:
  - name: http
    port: 80
    targetPort: http
  type: ClusterIP