apiVersion: apps/v1
kind: Deployment
metadata:
  name: infer
  namespace: xview
  labels: 
    app: infer
    part-of: xview
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels: 
      app: infer
  template:
    metadata:
      labels: 
        app: infer
        part-of: xview
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: infer
        image: localhost/infer:cpu
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 9000
          name: http
        envFrom:
        - configMapRef: 
            name: app-config
        - secretRef: 
            name: app-secret
        volumeMounts:
        - name: models
          mountPath: /models
        - name: outputs
          mountPath: /output
        - name: temp-storage
          mountPath: /tmp
        readinessProbe:
          httpGet: 
            path: "/healthz"
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet: 
            path: "/healthz"
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests: 
            cpu: "250m"
            memory: "512Mi"
          limits: 
            cpu: "1"
            memory: "2Gi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc
      - name: outputs
        persistentVolumeClaim:
          claimName: outputs-pvc
      - name: temp-storage
        emptyDir:
          sizeLimit: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: infer
  namespace: xview
  labels:
    app: infer
    part-of: xview
spec:
  selector: 
    app: infer
  ports: 
  - name: http
    port: 9000
    targetPort: http
  type: ClusterIP