apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ui
  namespace: xview
  labels:
    app: ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70