apiVersion: batch/v1
kind: Job
metadata:
  name: preprocess
  namespace: xview
  labels:
    app: preprocess
    part-of: xview
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: preprocess
        part-of: xview
    spec:
      restartPolicy: Never
      containers:
      - name: preprocess
        image: localhost/worker:dev
        imagePullPolicy: IfNotPresent
        command: ["python","-m","app.preprocess"]
        envFrom:
        - configMapRef: 
            name: app-config
        volumeMounts:
        - name: datasets
          mountPath: /data
        resources:
          requests: 
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "1Gi"
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-pvc