apiVersion: batch/v1
kind: Job
metadata:
  name: train
  namespace: xview
  labels:
    app: train
    part-of: xview
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: train
        part-of: xview
    spec:
      restartPolicy: Never
      containers:
      - name: train
        image: localhost/worker:dev
        imagePullPolicy: IfNotPresent
        command: ["python","-m","app.train"]
        envFrom:
        - configMapRef:
            name: app-config
        # These four override values in app-config when set via UI
        env:
        - name: BASE_WEIGHTS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BASE_WEIGHTS
        - name: EPOCHS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EPOCHS
        - name: IMG_SIZE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: IMG_SIZE
        - name: BATCH
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BATCH
        resources:
          requests: 
            cpu: "1"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        - name: datasets-pvc
          mountPath: /data     
        - name: models-pvc
          mountPath: /models  
      volumes:
      - name: datasets-pvc
        persistentVolumeClaim:
          claimName: datasets-pvc
      - name: models-pvc
        persistentVolumeClaim:
          claimName: models-pvc
