apiVersion: batch/v1
kind: Job
metadata:
  name: train
  namespace: xview
  labels:
    app: train
    part-of: xview
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: train
        part-of: xview
    spec:
      restartPolicy: Never
      containers:
      - name: train
        image: localhost/worker:dev
        imagePullPolicy: IfNotPresent
        command: ["python","-m","app.train"]
        envFrom:
        - configMapRef:
            name: app-config
        # These four will override the values in app-config, if provided in ui
        env:
        - name: BASE_WEIGHTS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BASE_WEIGHTS
        - name: EPOCHS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EPOCHS
        - name: IMG_SIZE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: IMG_SIZE
        - name: BATCH
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BATCH
        resources:
          requests: 
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "5Gi"
        volumeMounts:
        - name: datasets
          mountPath: /data
        - name: models
          mountPath: /models
      volumes:
        - name: datasets
          persistentVolumeClaim:
            claimName: datasets-pvc
        - name: models
          persistentVolumeClaim:
            claimName: models-pvc