apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui-service-account
  namespace: xview
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: xview
  name: ui-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ui-role-binding
  namespace: xview
subjects:
- kind: ServiceAccount
  name: ui-service-account
  namespace: xview
roleRef:
  kind: Role
  name: ui-role
  apiGroup: rbac.authorization.k8s.io
