# Assigns ui to be able to run jobs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ui-job-runner
  namespace: xview
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
