apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: xview
type: Opaque
stringData:
  # Authentication
  SECRET_KEY: "your-super-secret-key-change-in-production"
  redis-password: "redis123"
  
  # MinIO credentials for app access
  MINIO_ACCESS_KEY: "xview-app"
  MINIO_SECRET_KEY: "xview-app-secret-key"
  
  # Default admin credentials (change in production)
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin123"